var artjson = [
  {
    filename: 'albers-homage-square.jpg',
    title: 'placeholder',
    artist: 'placeholder',
    year: 'placeholder',
    details: 'placeholder'
  }, {
    filename: 'giotto-the-trial-by-fire.jpg',
    title: 'placeholder',
    artist: 'placeholder',
    year: 'placeholder',
    details: 'placeholder'
  }, {
    filename: 'kandinsky-composition-ix.jpg',
    title: 'placeholder',
    artist: 'placeholder',
    year: 'placeholder',
    details: 'placeholder'
  }, {
    filename: 'turner-storm-steam-boat.jpg',
    title: 'placeholder',
    artist: 'placeholder',
    year: 'placeholder',
    details: 'placeholder'
  }, {
    filename: 'basquiat-philistines.jpg',
    title: 'placeholder',
    artist: 'placeholder',
    year: 'placeholder',
    details: 'placeholder'
  }, {
    filename: 'goya-soup.jpg',
    title: 'placeholder',
    artist: 'placeholder',
    year: 'placeholder',
    details: 'placeholder'
  }, {
    filename: 'lissitzky-proun.jpg',
    title: 'placeholder',
    artist: 'placeholder',
    year: 'placeholder',
    details: 'placeholder'
  }, {
    filename: 'vaneyck-rnolfini.jpg',
    title: 'placeholder',
    artist: 'placeholder',
    year: 'placeholder',
    details: 'placeholder'
  }, {
    filename: 'chagall-birthday.jpg',
    title: 'placeholder',
    artist: 'placeholder',
    year: 'placeholder',
    details: 'placeholder'
  }, {
    filename: 'haring-keith-and-julia.jpg',
    title: 'placeholder',
    artist: 'placeholder',
    year: 'placeholder',
    details: 'placeholder'
  }, {
    filename: 'manet-at-bar.jpg',
    title: 'placeholder',
    artist: 'placeholder',
    year: 'placeholder',
    details: 'placeholder'
  }
]
